### PR TITLE
Added terser plugin for JS minification

### PR DESCRIPTION
**Pull request by alpmusti**
My `app.js` went `273KB` to `71KB` after using terser for minification. 

I've changed esbuild minify option true or false and nothing happened. So I've decided to add terser for minification and set to false esbuild minify option just in case.

### CODE REVIEW

**Comment by dangvanthanh** [comment]
Thank @alpmusti 

Before I was used `terser` for minification. If you want to see the file size after build you can use command:

```shell
$ npm run build
```

or if you using [pnpm](https://pnpm.js.org/)

```shell
$ pnpm run build
```

**Comment by alpmusti** [comment]
Hello @dangvanthanh ,
I've used `npm run build` command before adding terser for minication and before terser it produced `app.js` sized exactly`273 KB`. After adding terser and running `npm run build` command produced `app.js` sized `71KB`.

By the way, these numbers coming from my app which I've started using this repo.

**Comment by dangvanthanh** [comment]
@alpmusti 

This repository complier is 72KB, too

Screen Shot 2020-12-05 at 19 57 01

I will investigate and merged your PR.

**Comment by dangvanthanh** [comment]
Hi @alpmusti 

After checking with `terser` and `esbuild` the filesize after command `npm run build` is `~70kb`

I added `rollup-plugin-filesize` to help show filesize in the cli.

Screen Shot 2020-12-09 at 20 16 46

Thank you very much @alpmusti for your suggesttion.

**Pull request closed without merging**
